name: btcwallet_rpc
description: An RPC client for btcwallet.
version: 0.0.1
homepage: https://github.com/stevenroose/dart-btcwallet-rpc

environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  async: ^1.13.3
  grpc: ^0.2.1
  protobuf: ^0.7.0

dev_dependencies:
  test: ^0.12.0
